# Generated by Django 5.0.1 on 2024-01-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ReviewItem',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='ReviewRoom',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='ReviewSubject',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='ReviewTopic',
            new_name='Topic',
        ),
    ]
