# Generated by Django 5.0.1 on 2024-03-20 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_subject_date_time_created_subject_date_time_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
