# Generated by Django 5.0.1 on 2024-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_category_date_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
