# Generated by Django 5.0.3 on 2024-03-24 12:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_topic_path_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='path',
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
